name: centum
dependencies:
  - python>=3.9
  - setuptools
  - wheel
  - xarray
  - rioxarray
  - geopandas
  - pip
  - libgdal-hdf5
  - pip:
    - july
    - pooch
    - geocube
    - git+https://github.com/thoellrich/july.git@fix-mpl.cbook.MatplotlibDepreciationWarning
