# Jupyter Book configuration file
title: "Centum Documentation"
author: "Your Name"
description: "Documentation for the Centum package"
logo: "images/logo.png"

# Table of Contents configuration
toc:
  - file: intro
  - file: markdown
  - file: notebooks
  - file: markdown-notebooks
  - title: API Reference
    file: api/centum_api.md

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.napoleon'
  config:
    autosummary_generate: True
