# Jupyter Book configuration file
title: "Centum"
author: "Developers"
description: "Documentation for the Centum package"

# Sphinx configuration for Jupyter Book
sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.autosummary'
    - 'sphinx.ext.napoleon'
    - 'sphinx_gallery.gen_gallery'
  config:
    autosummary_generate: true

# Sphinx-Gallery configuration
sphinx_gallery:
  examples_dirs: "./datasets"  # Adjust this path to the actual location of your example notebooks
  gallery_dirs: "../gallery"  # The directory where gallery content will be saved
  download_all_examples: true  # Enable downloading of all examples in the gallery


