name: Deploy-doc

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
  workflow_dispatch:  # Allow manual triggering

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16

    - name: Install dependencies
      run: |
        pip install -r requirements_doc.txt
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ./docs/.
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.DOC_TOKEN}}
        publish_dir: ./_build/html
        publish_branch: gh-pages  # Correct input name
        allow_empty_commit: true
        
