name: Publish Python Package

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: centum  # Name of the Conda environment

    - name: Install dependencies
      run: |
        conda install --yes setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: centum
        path: dist/*

  publish:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job runs first
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download built source and wheel packages
        uses: actions/download-artifact@v4
        with:
          name: centum
          path: dist

      - name: Publish to Test PyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          repository_url: https://test.pypi.org/legacy/
          username: __token__  # Required for API token
          password: ${{ secrets.TEST_PYPI_TOKEN }}  # Use the secret here

      - name: Publish to PyPI
        # if: success() && (github.event_name == 'release' || github.event_name == 'workflow_dispatch')
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          repository_url: https://upload.pypi.org/legacy/
          username: __token__  # Required for API token
          password: ${{ secrets.PYPI_TOKEN }}  # Use the secret here
