name: Publish Python Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: centum  # Name of the Conda environment

    - name: Install dependencies
      run: |
        conda install --yes setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: centum
        path: dist/*
 
